// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: TugasParkirgRPC/gRPC/parkir.proto

package tugasparkirpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// request dan response buat masuk parkir
type MasukParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JenisKendaraan string `protobuf:"bytes,1,opt,name=jenisKendaraan,proto3" json:"jenisKendaraan,omitempty"`
	PelatNomor     string `protobuf:"bytes,2,opt,name=pelatNomor,proto3" json:"pelatNomor,omitempty"`
}

func (x *MasukParkir) Reset() {
	*x = MasukParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkir) ProtoMessage() {}

func (x *MasukParkir) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkir.ProtoReflect.Descriptor instead.
func (*MasukParkir) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{0}
}

func (x *MasukParkir) GetJenisKendaraan() string {
	if x != nil {
		return x.JenisKendaraan
	}
	return ""
}

func (x *MasukParkir) GetPelatNomor() string {
	if x != nil {
		return x.PelatNomor
	}
	return ""
}

type MasukParkirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasukParkir *MasukParkir `protobuf:"bytes,1,opt,name=masukParkir,proto3" json:"masukParkir,omitempty"`
}

func (x *MasukParkirRequest) Reset() {
	*x = MasukParkirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkirRequest) ProtoMessage() {}

func (x *MasukParkirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkirRequest.ProtoReflect.Descriptor instead.
func (*MasukParkirRequest) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{1}
}

func (x *MasukParkirRequest) GetMasukParkir() *MasukParkir {
	if x != nil {
		return x.MasukParkir
	}
	return nil
}

type MasukParkirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeneratedId int64 `protobuf:"varint,1,opt,name=generatedId,proto3" json:"generatedId,omitempty"`
}

func (x *MasukParkirResponse) Reset() {
	*x = MasukParkirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkirResponse) ProtoMessage() {}

func (x *MasukParkirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkirResponse.ProtoReflect.Descriptor instead.
func (*MasukParkirResponse) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{2}
}

func (x *MasukParkirResponse) GetGeneratedId() int64 {
	if x != nil {
		return x.GeneratedId
	}
	return 0
}

// request dan response buat keluar parkir
type KeluarParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdKeluar int64 `protobuf:"varint,1,opt,name=idKeluar,proto3" json:"idKeluar,omitempty"`
}

func (x *KeluarParkir) Reset() {
	*x = KeluarParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkir) ProtoMessage() {}

func (x *KeluarParkir) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkir.ProtoReflect.Descriptor instead.
func (*KeluarParkir) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{3}
}

func (x *KeluarParkir) GetIdKeluar() int64 {
	if x != nil {
		return x.IdKeluar
	}
	return 0
}

type KeluarParkirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeluarParkir *KeluarParkir `protobuf:"bytes,1,opt,name=keluarParkir,proto3" json:"keluarParkir,omitempty"`
}

func (x *KeluarParkirRequest) Reset() {
	*x = KeluarParkirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkirRequest) ProtoMessage() {}

func (x *KeluarParkirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkirRequest.ProtoReflect.Descriptor instead.
func (*KeluarParkirRequest) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{4}
}

func (x *KeluarParkirRequest) GetKeluarParkir() *KeluarParkir {
	if x != nil {
		return x.KeluarParkir
	}
	return nil
}

type KeluarParkirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalBiaya int64 `protobuf:"varint,1,opt,name=totalBiaya,proto3" json:"totalBiaya,omitempty"`
}

func (x *KeluarParkirResponse) Reset() {
	*x = KeluarParkirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkirResponse) ProtoMessage() {}

func (x *KeluarParkirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkirResponse.ProtoReflect.Descriptor instead.
func (*KeluarParkirResponse) Descriptor() ([]byte, []int) {
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP(), []int{5}
}

func (x *KeluarParkirResponse) GetTotalBiaya() int64 {
	if x != nil {
		return x.TotalBiaya
	}
	return 0
}

var File_TugasParkirgRPC_gRPC_parkir_proto protoreflect.FileDescriptor

var file_TugasParkirgRPC_gRPC_parkir_proto_rawDesc = []byte{
	0x0a, 0x21, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x67, 0x52, 0x50,
	0x43, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72,
	0x22, 0x55, 0x0a, 0x0b, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12,
	0x26, 0x0a, 0x0e, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x4b, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x61, 0x61,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x4b, 0x65,
	0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x6c, 0x61, 0x74,
	0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x65, 0x6c,
	0x61, 0x74, 0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x22, 0x50, 0x0a, 0x12, 0x4d, 0x61, 0x73, 0x75, 0x6b,
	0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x0b, 0x6d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72,
	0x2e, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x0b, 0x6d, 0x61,
	0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x22, 0x37, 0x0a, 0x13, 0x4d, 0x61, 0x73,
	0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0c, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x22, 0x54,
	0x0a, 0x13, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50,
	0x61, 0x72, 0x6b, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x54, 0x75,
	0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72,
	0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x0c, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x22, 0x36, 0x0a, 0x14, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x61, 0x79, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x61, 0x79, 0x61, 0x32, 0xba, 0x01, 0x0a,
	0x0d, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52,
	0x0a, 0x0b, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x1f, 0x2e,
	0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x4d, 0x61, 0x73, 0x75,
	0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x4d, 0x61, 0x73,
	0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x12, 0x20, 0x2e, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72,
	0x2e, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x54, 0x75, 0x67, 0x61, 0x73, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x2e, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x74, 0x75, 0x67,
	0x61, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_TugasParkirgRPC_gRPC_parkir_proto_rawDescOnce sync.Once
	file_TugasParkirgRPC_gRPC_parkir_proto_rawDescData = file_TugasParkirgRPC_gRPC_parkir_proto_rawDesc
)

func file_TugasParkirgRPC_gRPC_parkir_proto_rawDescGZIP() []byte {
	file_TugasParkirgRPC_gRPC_parkir_proto_rawDescOnce.Do(func() {
		file_TugasParkirgRPC_gRPC_parkir_proto_rawDescData = protoimpl.X.CompressGZIP(file_TugasParkirgRPC_gRPC_parkir_proto_rawDescData)
	})
	return file_TugasParkirgRPC_gRPC_parkir_proto_rawDescData
}

var file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_TugasParkirgRPC_gRPC_parkir_proto_goTypes = []interface{}{
	(*MasukParkir)(nil),          // 0: TugasParkir.MasukParkir
	(*MasukParkirRequest)(nil),   // 1: TugasParkir.MasukParkirRequest
	(*MasukParkirResponse)(nil),  // 2: TugasParkir.MasukParkirResponse
	(*KeluarParkir)(nil),         // 3: TugasParkir.KeluarParkir
	(*KeluarParkirRequest)(nil),  // 4: TugasParkir.KeluarParkirRequest
	(*KeluarParkirResponse)(nil), // 5: TugasParkir.KeluarParkirResponse
}
var file_TugasParkirgRPC_gRPC_parkir_proto_depIdxs = []int32{
	0, // 0: TugasParkir.MasukParkirRequest.masukParkir:type_name -> TugasParkir.MasukParkir
	3, // 1: TugasParkir.KeluarParkirRequest.keluarParkir:type_name -> TugasParkir.KeluarParkir
	1, // 2: TugasParkir.parkirService.MasukParkir:input_type -> TugasParkir.MasukParkirRequest
	4, // 3: TugasParkir.parkirService.KeluarParkir:input_type -> TugasParkir.KeluarParkirRequest
	2, // 4: TugasParkir.parkirService.MasukParkir:output_type -> TugasParkir.MasukParkirResponse
	5, // 5: TugasParkir.parkirService.KeluarParkir:output_type -> TugasParkir.KeluarParkirResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TugasParkirgRPC_gRPC_parkir_proto_init() }
func file_TugasParkirgRPC_gRPC_parkir_proto_init() {
	if File_TugasParkirgRPC_gRPC_parkir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TugasParkirgRPC_gRPC_parkir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TugasParkirgRPC_gRPC_parkir_proto_goTypes,
		DependencyIndexes: file_TugasParkirgRPC_gRPC_parkir_proto_depIdxs,
		MessageInfos:      file_TugasParkirgRPC_gRPC_parkir_proto_msgTypes,
	}.Build()
	File_TugasParkirgRPC_gRPC_parkir_proto = out.File
	file_TugasParkirgRPC_gRPC_parkir_proto_rawDesc = nil
	file_TugasParkirgRPC_gRPC_parkir_proto_goTypes = nil
	file_TugasParkirgRPC_gRPC_parkir_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParkirServiceClient is the client API for ParkirService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkirServiceClient interface {
	MasukParkir(ctx context.Context, in *MasukParkirRequest, opts ...grpc.CallOption) (*MasukParkirResponse, error)
	KeluarParkir(ctx context.Context, in *KeluarParkirRequest, opts ...grpc.CallOption) (*KeluarParkirResponse, error)
}

type parkirServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkirServiceClient(cc grpc.ClientConnInterface) ParkirServiceClient {
	return &parkirServiceClient{cc}
}

func (c *parkirServiceClient) MasukParkir(ctx context.Context, in *MasukParkirRequest, opts ...grpc.CallOption) (*MasukParkirResponse, error) {
	out := new(MasukParkirResponse)
	err := c.cc.Invoke(ctx, "/TugasParkir.parkirService/MasukParkir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkirServiceClient) KeluarParkir(ctx context.Context, in *KeluarParkirRequest, opts ...grpc.CallOption) (*KeluarParkirResponse, error) {
	out := new(KeluarParkirResponse)
	err := c.cc.Invoke(ctx, "/TugasParkir.parkirService/KeluarParkir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkirServiceServer is the server API for ParkirService service.
type ParkirServiceServer interface {
	MasukParkir(context.Context, *MasukParkirRequest) (*MasukParkirResponse, error)
	KeluarParkir(context.Context, *KeluarParkirRequest) (*KeluarParkirResponse, error)
}

// UnimplementedParkirServiceServer can be embedded to have forward compatible implementations.
type UnimplementedParkirServiceServer struct {
}

func (*UnimplementedParkirServiceServer) MasukParkir(context.Context, *MasukParkirRequest) (*MasukParkirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasukParkir not implemented")
}
func (*UnimplementedParkirServiceServer) KeluarParkir(context.Context, *KeluarParkirRequest) (*KeluarParkirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeluarParkir not implemented")
}

func RegisterParkirServiceServer(s *grpc.Server, srv ParkirServiceServer) {
	s.RegisterService(&_ParkirService_serviceDesc, srv)
}

func _ParkirService_MasukParkir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasukParkirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkirServiceServer).MasukParkir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TugasParkir.parkirService/MasukParkir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkirServiceServer).MasukParkir(ctx, req.(*MasukParkirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkirService_KeluarParkir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeluarParkirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkirServiceServer).KeluarParkir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TugasParkir.parkirService/KeluarParkir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkirServiceServer).KeluarParkir(ctx, req.(*KeluarParkirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParkirService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TugasParkir.parkirService",
	HandlerType: (*ParkirServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MasukParkir",
			Handler:    _ParkirService_MasukParkir_Handler,
		},
		{
			MethodName: "KeluarParkir",
			Handler:    _ParkirService_KeluarParkir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TugasParkirgRPC/gRPC/parkir.proto",
}
