// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: Proto/parkir.proto

package parkirpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MasukParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JenisKendaraan string `protobuf:"bytes,1,opt,name=JenisKendaraan,proto3" json:"JenisKendaraan,omitempty"`
	PelatNomor     string `protobuf:"bytes,2,opt,name=PelatNomor,proto3" json:"PelatNomor,omitempty"`
}

func (x *MasukParkir) Reset() {
	*x = MasukParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkir) ProtoMessage() {}

func (x *MasukParkir) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkir.ProtoReflect.Descriptor instead.
func (*MasukParkir) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{0}
}

func (x *MasukParkir) GetJenisKendaraan() string {
	if x != nil {
		return x.JenisKendaraan
	}
	return ""
}

func (x *MasukParkir) GetPelatNomor() string {
	if x != nil {
		return x.PelatNomor
	}
	return ""
}

type MasukParkirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasukParkir *MasukParkir `protobuf:"bytes,1,opt,name=masukParkir,proto3" json:"masukParkir,omitempty"`
}

func (x *MasukParkirRequest) Reset() {
	*x = MasukParkirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkirRequest) ProtoMessage() {}

func (x *MasukParkirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkirRequest.ProtoReflect.Descriptor instead.
func (*MasukParkirRequest) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{1}
}

func (x *MasukParkirRequest) GetMasukParkir() *MasukParkir {
	if x != nil {
		return x.MasukParkir
	}
	return nil
}

type MasukParkirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeneratedId int64 `protobuf:"varint,1,opt,name=GeneratedId,proto3" json:"GeneratedId,omitempty"`
}

func (x *MasukParkirResponse) Reset() {
	*x = MasukParkirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasukParkirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasukParkirResponse) ProtoMessage() {}

func (x *MasukParkirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasukParkirResponse.ProtoReflect.Descriptor instead.
func (*MasukParkirResponse) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{2}
}

func (x *MasukParkirResponse) GetGeneratedId() int64 {
	if x != nil {
		return x.GeneratedId
	}
	return 0
}

type KeluarParkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdKeluar int64 `protobuf:"varint,1,opt,name=IdKeluar,proto3" json:"IdKeluar,omitempty"`
}

func (x *KeluarParkir) Reset() {
	*x = KeluarParkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkir) ProtoMessage() {}

func (x *KeluarParkir) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkir.ProtoReflect.Descriptor instead.
func (*KeluarParkir) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{3}
}

func (x *KeluarParkir) GetIdKeluar() int64 {
	if x != nil {
		return x.IdKeluar
	}
	return 0
}

type KeluarParkirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeluarParkir *KeluarParkir `protobuf:"bytes,1,opt,name=keluarParkir,proto3" json:"keluarParkir,omitempty"`
}

func (x *KeluarParkirRequest) Reset() {
	*x = KeluarParkirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkirRequest) ProtoMessage() {}

func (x *KeluarParkirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkirRequest.ProtoReflect.Descriptor instead.
func (*KeluarParkirRequest) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{4}
}

func (x *KeluarParkirRequest) GetKeluarParkir() *KeluarParkir {
	if x != nil {
		return x.KeluarParkir
	}
	return nil
}

type KeluarParkirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalBiaya int64 `protobuf:"varint,1,opt,name=TotalBiaya,proto3" json:"TotalBiaya,omitempty"`
}

func (x *KeluarParkirResponse) Reset() {
	*x = KeluarParkirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_parkir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeluarParkirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeluarParkirResponse) ProtoMessage() {}

func (x *KeluarParkirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_parkir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeluarParkirResponse.ProtoReflect.Descriptor instead.
func (*KeluarParkirResponse) Descriptor() ([]byte, []int) {
	return file_Proto_parkir_proto_rawDescGZIP(), []int{5}
}

func (x *KeluarParkirResponse) GetTotalBiaya() int64 {
	if x != nil {
		return x.TotalBiaya
	}
	return 0
}

var File_Proto_parkir_proto protoreflect.FileDescriptor

var file_Proto_parkir_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x5f, 0x67, 0x52, 0x50,
	0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x55, 0x0a, 0x0b, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50,
	0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x4b, 0x65,
	0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4a,
	0x65, 0x6e, 0x69, 0x73, 0x4b, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x61, 0x61, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x50, 0x65, 0x6c, 0x61, 0x74, 0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x50, 0x65, 0x6c, 0x61, 0x74, 0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x22, 0x65, 0x0a,
	0x12, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x0b, 0x6d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69,
	0x72, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x73, 0x75,
	0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x0b, 0x6d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x22, 0x37, 0x0a, 0x13, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72,
	0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x22, 0x2a, 0x0a,
	0x0c, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x64, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x49, 0x64, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x22, 0x69, 0x0a, 0x13, 0x4b, 0x65, 0x6c,
	0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x52, 0x0a, 0x0c, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x5f,
	0x67, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72,
	0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x0c, 0x6b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x22, 0x36, 0x0a, 0x14, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61,
	0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x61, 0x79, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x61, 0x79, 0x61, 0x32, 0x9e, 0x02, 0x0a,
	0x0d, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x83,
	0x01, 0x0a, 0x10, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x34, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x5f, 0x67, 0x52, 0x50,
	0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x73, 0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x50, 0x61, 0x72, 0x6b,
	0x69, 0x72, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x73,
	0x75, 0x6b, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x86, 0x01, 0x0a, 0x11, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50,
	0x61, 0x72, 0x6b, 0x69, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x35, 0x2e, 0x50, 0x61, 0x72,
	0x6b, 0x69, 0x72, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4b, 0x65,
	0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x36, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x5f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4b, 0x65, 0x6c, 0x75, 0x61, 0x72, 0x50, 0x61, 0x72, 0x6b, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Proto_parkir_proto_rawDescOnce sync.Once
	file_Proto_parkir_proto_rawDescData = file_Proto_parkir_proto_rawDesc
)

func file_Proto_parkir_proto_rawDescGZIP() []byte {
	file_Proto_parkir_proto_rawDescOnce.Do(func() {
		file_Proto_parkir_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_parkir_proto_rawDescData)
	})
	return file_Proto_parkir_proto_rawDescData
}

var file_Proto_parkir_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Proto_parkir_proto_goTypes = []interface{}{
	(*MasukParkir)(nil),          // 0: Parkir_gRPC_Server_Streaming_rpc.MasukParkir
	(*MasukParkirRequest)(nil),   // 1: Parkir_gRPC_Server_Streaming_rpc.MasukParkirRequest
	(*MasukParkirResponse)(nil),  // 2: Parkir_gRPC_Server_Streaming_rpc.MasukParkirResponse
	(*KeluarParkir)(nil),         // 3: Parkir_gRPC_Server_Streaming_rpc.KeluarParkir
	(*KeluarParkirRequest)(nil),  // 4: Parkir_gRPC_Server_Streaming_rpc.KeluarParkirRequest
	(*KeluarParkirResponse)(nil), // 5: Parkir_gRPC_Server_Streaming_rpc.KeluarParkirResponse
}
var file_Proto_parkir_proto_depIdxs = []int32{
	0, // 0: Parkir_gRPC_Server_Streaming_rpc.MasukParkirRequest.masukParkir:type_name -> Parkir_gRPC_Server_Streaming_rpc.MasukParkir
	3, // 1: Parkir_gRPC_Server_Streaming_rpc.KeluarParkirRequest.keluarParkir:type_name -> Parkir_gRPC_Server_Streaming_rpc.KeluarParkir
	1, // 2: Parkir_gRPC_Server_Streaming_rpc.ParkirService.MasukParkirProto:input_type -> Parkir_gRPC_Server_Streaming_rpc.MasukParkirRequest
	4, // 3: Parkir_gRPC_Server_Streaming_rpc.ParkirService.KeluarParkirProto:input_type -> Parkir_gRPC_Server_Streaming_rpc.KeluarParkirRequest
	2, // 4: Parkir_gRPC_Server_Streaming_rpc.ParkirService.MasukParkirProto:output_type -> Parkir_gRPC_Server_Streaming_rpc.MasukParkirResponse
	5, // 5: Parkir_gRPC_Server_Streaming_rpc.ParkirService.KeluarParkirProto:output_type -> Parkir_gRPC_Server_Streaming_rpc.KeluarParkirResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Proto_parkir_proto_init() }
func file_Proto_parkir_proto_init() {
	if File_Proto_parkir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_parkir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_parkir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_parkir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasukParkirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_parkir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_parkir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_parkir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeluarParkirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_parkir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Proto_parkir_proto_goTypes,
		DependencyIndexes: file_Proto_parkir_proto_depIdxs,
		MessageInfos:      file_Proto_parkir_proto_msgTypes,
	}.Build()
	File_Proto_parkir_proto = out.File
	file_Proto_parkir_proto_rawDesc = nil
	file_Proto_parkir_proto_goTypes = nil
	file_Proto_parkir_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParkirServiceClient is the client API for ParkirService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkirServiceClient interface {
	MasukParkirProto(ctx context.Context, in *MasukParkirRequest, opts ...grpc.CallOption) (ParkirService_MasukParkirProtoClient, error)
	KeluarParkirProto(ctx context.Context, in *KeluarParkirRequest, opts ...grpc.CallOption) (ParkirService_KeluarParkirProtoClient, error)
}

type parkirServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkirServiceClient(cc grpc.ClientConnInterface) ParkirServiceClient {
	return &parkirServiceClient{cc}
}

func (c *parkirServiceClient) MasukParkirProto(ctx context.Context, in *MasukParkirRequest, opts ...grpc.CallOption) (ParkirService_MasukParkirProtoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ParkirService_serviceDesc.Streams[0], "/Parkir_gRPC_Server_Streaming_rpc.ParkirService/MasukParkirProto", opts...)
	if err != nil {
		return nil, err
	}
	x := &parkirServiceMasukParkirProtoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ParkirService_MasukParkirProtoClient interface {
	Recv() (*MasukParkirResponse, error)
	grpc.ClientStream
}

type parkirServiceMasukParkirProtoClient struct {
	grpc.ClientStream
}

func (x *parkirServiceMasukParkirProtoClient) Recv() (*MasukParkirResponse, error) {
	m := new(MasukParkirResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *parkirServiceClient) KeluarParkirProto(ctx context.Context, in *KeluarParkirRequest, opts ...grpc.CallOption) (ParkirService_KeluarParkirProtoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ParkirService_serviceDesc.Streams[1], "/Parkir_gRPC_Server_Streaming_rpc.ParkirService/KeluarParkirProto", opts...)
	if err != nil {
		return nil, err
	}
	x := &parkirServiceKeluarParkirProtoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ParkirService_KeluarParkirProtoClient interface {
	Recv() (*KeluarParkirResponse, error)
	grpc.ClientStream
}

type parkirServiceKeluarParkirProtoClient struct {
	grpc.ClientStream
}

func (x *parkirServiceKeluarParkirProtoClient) Recv() (*KeluarParkirResponse, error) {
	m := new(KeluarParkirResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ParkirServiceServer is the server API for ParkirService service.
type ParkirServiceServer interface {
	MasukParkirProto(*MasukParkirRequest, ParkirService_MasukParkirProtoServer) error
	KeluarParkirProto(*KeluarParkirRequest, ParkirService_KeluarParkirProtoServer) error
}

// UnimplementedParkirServiceServer can be embedded to have forward compatible implementations.
type UnimplementedParkirServiceServer struct {
}

func (*UnimplementedParkirServiceServer) MasukParkirProto(*MasukParkirRequest, ParkirService_MasukParkirProtoServer) error {
	return status.Errorf(codes.Unimplemented, "method MasukParkirProto not implemented")
}
func (*UnimplementedParkirServiceServer) KeluarParkirProto(*KeluarParkirRequest, ParkirService_KeluarParkirProtoServer) error {
	return status.Errorf(codes.Unimplemented, "method KeluarParkirProto not implemented")
}

func RegisterParkirServiceServer(s *grpc.Server, srv ParkirServiceServer) {
	s.RegisterService(&_ParkirService_serviceDesc, srv)
}

func _ParkirService_MasukParkirProto_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MasukParkirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParkirServiceServer).MasukParkirProto(m, &parkirServiceMasukParkirProtoServer{stream})
}

type ParkirService_MasukParkirProtoServer interface {
	Send(*MasukParkirResponse) error
	grpc.ServerStream
}

type parkirServiceMasukParkirProtoServer struct {
	grpc.ServerStream
}

func (x *parkirServiceMasukParkirProtoServer) Send(m *MasukParkirResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ParkirService_KeluarParkirProto_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeluarParkirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParkirServiceServer).KeluarParkirProto(m, &parkirServiceKeluarParkirProtoServer{stream})
}

type ParkirService_KeluarParkirProtoServer interface {
	Send(*KeluarParkirResponse) error
	grpc.ServerStream
}

type parkirServiceKeluarParkirProtoServer struct {
	grpc.ServerStream
}

func (x *parkirServiceKeluarParkirProtoServer) Send(m *KeluarParkirResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ParkirService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Parkir_gRPC_Server_Streaming_rpc.ParkirService",
	HandlerType: (*ParkirServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MasukParkirProto",
			Handler:       _ParkirService_MasukParkirProto_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "KeluarParkirProto",
			Handler:       _ParkirService_KeluarParkirProto_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Proto/parkir.proto",
}
